name: "Dependaction - Group By"
description: "Groups dependency packages by scope, latest version, etc."
inputs:
  directories: # root directories to search for deps
    description: "Root directories to search for dependency packages"
    required: false
    default: ""
  exclude-packages: # list of packages to exclude
    description: "Packages to exclude"
    required: false
    default: ""
  limit: # limit
    description: "Limit (for testing)"
    required: false
    default: ""
outputs:
  matrix: # id of output
    description: "A matrix of grouped dependency packages"
    value: ${{ steps.group-by-script.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - id: group-by-script
      run: echo "::set-output name=matrix::$(node ${{ github.action_path }}/dist/index.js) # does this set an output var?
      shell: bash
